version: '3.8'

services:
  service-db:
    container_name: todo-service-db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.4-rc
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data
    command: redis-server --save 20 1  --requirepass cXdlcnR5MTIzNDVxd2VydHkxMjM0NQ==

volumes:
  pg_data:
  cache:
    driver: local